apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: '89.2.3'
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: flux-system
    values:
        alertmanager:
            enabled: true
            alertmanagerSpec:
                secrets:
                    - alertmanager-secret
            config:
                global: {}
                route:
                    receiver: discord
                    group_by:
                        - alertname
                        - severity
                    group_wait: 30s
                    group_interval: 5m
                    repeat_interval: 12h
                receivers:
                    - name: "null"
                    - name: discord
                      discord_configs:
                        - webhook_url: ENC[AES256_GCM,data:/vVUFqw5IXM43Yh/Yr49BLuAQkG2BmfnR34HLhH6321rKY0vSJ47xpWDHjhrghDpJdhCS1JmBpJ8jpGjDkTnxaeV50SLfgRQp36VoFIxqeEcUfxQbyTm32Mns5mmTPjM3P5qHn4otg+EE0+UoYz327J00oI3zzY85g==,iv:EoUutNr2S3PYiUUOMmNjeWQlkONYU20DGYlncGLxYJk=,tag:suWDjptjPG9wjHIyFCvV4Q==,type:str]
                          send_resolved: true
                          title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
                          message: |
                            {{ range .Alerts }}
                            **Severity:** {{ .Labels.severity }}
                            **Summary:** {{ .Annotations.summary }}
                            {{ .Annotations.description }}
                            {{ end }}
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - alertmanager.phoenyxlab.xyz
                tls:
                    - hosts:
                        - alertmanager.phoenyxlab.xyz
        cAdvisor:
            enabled: true
        kubeApiServer:
            serviceMonitor:
                interval: 60s
                metricRelabelings:
                    - action: drop
                      regex: (etcd_request|apiserver_request_slo|apiserver_request_sli|apiserver_request)_duration_seconds_bucket;(0\.15|0\.2|0\.3|0\.35|0\.4|0\.45|0\.6|0\.7|0\.8|0\.9|1\.25|1\.5|1\.75|2|3|3\.5|4|4\.5|6|7|8|9|15|20|40|45|50)(\.0)?
                      sourceLabels:
                          - __name__
                          - le
                    - action: drop
                      regex: apiserver_(request_body_size_bytes_bucket|response_sizes_bucket|watch_list_duration_seconds_bucket|watch_cache_read_wait_seconds_bucket|watch_events_sizes_bucket|admission_controller_admission_duration_seconds_bucket)
                      sourceLabels:
                          - __name__
                    - action: drop
                      regex: apiserver_flowcontrol_.*
                      sourceLabels:
                          - __name__
        kubeStateMetrics:
            enabled: true
        kubelet:
            serviceMonitor:
                interval: 60s
        grafana:
            enabled: true
            adminUser: wolf
            adminPassword: ENC[AES256_GCM,data:NVfu/i3GreruajM=,iv:9h8RNnyVoSrQPNK5eNpePRRpjTguAPEX/J6q2x6us2Y=,tag:vzaswOomH2ubJmX6AeUjIA==,type:str]
            persistence:
                enabled: true
                type: pvc
                size: 10Gi
                accessModes:
                    - ReadWriteOnce
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.phoenyxlab.xyz
                tls:
                    - hosts:
                        - grafana.phoenyxlab.xyz
        prometheus:
            enabled: true
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - prometheus.phoenyxlab.xyz
                tls:
                    - hosts:
                        - prometheus.phoenyxlab.xyz
            prometheusSpec:
                resources:
                    requests:
                        cpu: 250m
                        memory: 512Mi
                    limits:
                        memory: 1Gi
        prometheus-node-exporter:
            enabled: true
        kubeProxy:
            enabled: false
        kubeControllerManager:
            enabled: false
        kubeScheduler:
            enabled: false
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTTJTRzRxOVNxbDRNNXVp
            M2taLzc0TERlYjNYUWJQUEF0SUpMQmptM1FVCmtISEx0cDNMOTdadHBtM3JOb0l4
            QUpaeDdZRC8rc1k1czlLSnRxOW1wK0UKLS0tIENyOHlQM0h0V013SlhGZnBNcHJG
            NHRKYW1sMWppT0JrUWxlVVQzc2hBWm8KZL3ygSeAr2rZdRqSZV3Zmya5kSeMTEq7
            aXYOqZ8dB0N3Sxwe3ulxUbMCF3AGh5yjExjrSx/Fb8FDHQWyGRjGzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    encrypted_regex: ^(webhook_url|adminPassword)$
    lastmodified: "2026-06-27T16:32:59Z"
    mac: ENC[AES256_GCM,data:DrxeMfoHW0cLVm76XNBcnG4phM+EecLX3tjWBrOTrBFM2Aa4O+L7pBlnv5sIYOPxrpEeYP9BZYciORraLhPgjw+0oVa31Pixx2jsbMmsOZM9E1yLNhbCp4rb2tVm1FLWeRavfC7ykCowc2WGm4xUCoeFodpIcbnMF95d0wPG7Q8=,iv:iE1SSDM4lUF+k+sk37wKoxGiyTvxI8y+eoCNN6y7Z3c=,tag:/U++BfXshV3s9eWQJGxA+w==,type:str]
    version: 3.13.1
