apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
  labels:
    app: lidarr
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/instance: lidarr
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
        app.kubernetes.io/name: lidarr
        app.kubernetes.io/instance: lidarr
        app.kubernetes.io/part-of: phoenyxlab
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:3.1.6-nightly
          ports:
            - containerPort: 8686
          livenessProbe:
            tcpSocket:
              port: 8686
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 8686
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads-qbittorrent
              mountPath: /downloads/qbittorrent
            - name: downloads-slskd
              mountPath: /downloads/completed
            - name: media
              mountPath: /music
        - name: exportarr-lidarr
          image: ghcr.io/onedr0p/exportarr:v2.3.0
          args:
            - lidarr
          env:
            - name: URL
              value: "http://lidarr.media:8686"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: lidarr-secret
                  key: LIDARR_API_KEY
          ports:
            - containerPort: 9707
              name: metrics
          livenessProbe:
            tcpSocket:
              port: 9707
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 9707
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: downloads-qbittorrent
          hostPath:
            path: /downloads/qbittorrent
        - name: downloads-slskd
          hostPath:
            path: /downloads/slskd/completed
        - name: media
          hostPath:
            path: /media/music
