apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: infra
  labels:
    app: homepage
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
        app.kubernetes.io/name: homepage
        app.kubernetes.io/instance: homepage
        app.kubernetes.io/part-of: phoenyxlab
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v2.4.0
          ports:
            - containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.phoenyxlab.xyz,gethomepage.dev"
          envFrom:
            - secretRef:
                name: homepage-apis-secret
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
            - name: assets
              mountPath: /app/public/images
      volumes:
        - name: config
          configMap:
            name: homepage-configmap
        - name: logs
          emptyDir: {}
        - name: assets
          persistentVolumeClaim:
            claimName: homepage-assets
