apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: downloads
  labels:
    app: qbittorrent
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        app.kubernetes.io/name: qbittorrent
        app.kubernetes.io/instance: qbittorrent
        app.kubernetes.io/part-of: phoenyxlab
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.2.4
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
            - name: WEBUI_PORT
              value: "8080"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads

        - name: qbittorrent-exporter
          image: ghcr.io/martabal/qbittorrent-exporter:v2.0.3
          env:
            - name: QBITTORRENT_BASE_URL
              value: "http://qbittorrent.downloads:8080"
            - name: QBITTORRENT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-secret
                  key: QBITTORRENT_API_KEY
          ports:
            - containerPort: 8090
              name: metrics
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:v3.41
          restartPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: >-
                /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
          envFrom:
            - configMapRef:
                name: gluetun-config
            - secretRef:
                name: gluetun-secret
          volumeMounts:
            - name: tun-device
              mountPath: /dev/net/tun
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          hostPath:
            path: /downloads/qbittorrent
            type: Directory
        - name: tun-device
          hostPath:
            path: /dev/net/tun
            type: CharDevice
