apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
  labels:
    app: navidrome
    app.kubernetes.io/name: navidrome
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
        app.kubernetes.io/name: navidrome
        app.kubernetes.io/instance: navidrome
        app.kubernetes.io/part-of: phoenyxlab
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome:0.64.0
          env:
            - name: ND_PROMETHEUS_ENABLED
              value: "true"
            - name: ND_PROMETHEUS_METRICSPATH
              value: "/metrics"
          ports:
            - containerPort: 4533
          livenessProbe:
            tcpSocket:
              port: 4533
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 4533
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /data
            - name: music
              mountPath: /music
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: navidrome-config
        - name: music
          hostPath:
            path: /media/music
