apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr
        app.kubernetes.io/part-of: phoenyxlab
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.4.4
          ports:
            - containerPort: 7878
          livenessProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /media
            - name: media
              mountPath: /movies
        - name: exportarr-radarr
          image: ghcr.io/onedr0p/exportarr:v2.3.0
          args:
            - radarr
          env:
            - name: URL
              value: "http://radarr.media:7878"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: radarr-secret
                  key: RADARR_API_KEY
          ports:
            - containerPort: 9707
              name: metrics
          livenessProbe:
            tcpSocket:
              port: 9707
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 9707
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: downloads
          hostPath:
            path: /downloads/qbittorrent
        - name: media
          hostPath:
            path: /media/movies
