apiVersion: apps/v1
kind: Deployment
metadata:
  name: glances
  namespace: monitoring
  labels:
    app: glances
    app.kubernetes.io/name: glances
    app.kubernetes.io/instance: glances
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
        app.kubernetes.io/name: glances
        app.kubernetes.io/instance: glances
        app.kubernetes.io/part-of: phoenyxlab
        app.kubernetes.io/managed-by: kustomize
    spec:
      hostPID: true
      containers:
        - name: glances
          image: nicolargo/glances:4.5.7
          env:
            - name: GLANCES_OPT
              value: "-w --enable-plugin smart"
            - name: TZ
              value: "Asia/Kolkata"
            - name: PYTHONCACHEPREFIX
              value: "/tmp/py_caches"
          ports:
            - containerPort: 61208
          livenessProbe:
            tcpSocket:
              port: 61208
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 61208
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: config
              mountPath: /glances/conf
            - name: os-release
              mountPath: /etc/os-release
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
        - name: os-release
          hostPath:
            path: /etc/os-release
            type: File
        - name: config
          persistentVolumeClaim:
            claimName: glances-config
        - name: tmp
          emptyDir: {}
